project_name: example-go-release
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux
    goarch:
      - amd64
snapshot:
  name_template: '{{ .Version }}-devel'
release:
  github:
    owner: RajeshMohanty23
    name: golang-release-action
  name_template: "{{ .Tag }}"
  mode: append
  header: |
    Welcome to this new release!
  footer: |
    Those were the changes on {{ incpatch .Tag }}!