project_name: example-go-release
builds:
  - env: [CGO_ENABLED=0]
    goos:
      - linux

    goarch:
      - amd64

release:
  name_template: "{{ incpatch .Tag }}"
  mode:  append
  header: |
    Welcome to this new release!
  footer: |
    Those were the changes on {{ .Tag }}!